[package]
name = "binding-c"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[lib]
crate-type = ["rlib", "staticlib", "cdylib"]

[dependencies]
cqlib-tianyan = { path = "../cqlib-tianyan", version = "0.1.0-beta.1" }
cqlib-core.workspace = true
serde_json.workspace = true

[build-dependencies]
cbindgen = "0.29"
