/* Generated by cbindgen. Do not edit manually. */

#ifndef CQLIB_TIANYAN_H
#define CQLIB_TIANYAN_H

#pragma once

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
/* ── Opaque handle types ─────────────────────────────────────────────────── */

/** Opaque handle for TianyanBackend.  Use tianyan_backend_* functions. */
typedef struct TianyanBackendC TianyanBackendC;

/** Opaque handle for TianyanTask.  Use tianyan_task_* functions. */
typedef struct TianyanTaskC TianyanTaskC;

/** Opaque list of execution results.  Use tianyan_result_* functions. */
typedef struct TianyanResultList TianyanResultList;


/*
 Opaque wrapper around [`TianyanBackend`] for C callers.
 */
typedef struct TianyanBackendC TianyanBackendC;

/*
 Opaque handle to the Tianyan platform client.

 Obtain via `tianyan_platform_login()` or `tianyan_platform_from_credentials()`.
 Must be freed with `tianyan_platform_free()`.
 */
typedef struct TianyanPlatformC TianyanPlatformC;

/*
 A list of [`ExecutionResult`] returned by `tianyan_task_wait()` / `tianyan_task_status_snapshot()`.

 `task_ids` is pre-built as a parallel `Vec<CString>` so that
 `tianyan_result_task_id()` can return a stable `*const c_char` without
 requiring the caller to free each individual string.
 */
typedef struct TianyanResultList TianyanResultList;

/*
 Opaque wrapper around [`TaskHandle`] for C callers.
 */
typedef struct TianyanTaskC TianyanTaskC;

/*
 Runtime configuration for the Tianyan platform client.

 All pointer fields may be `NULL` to use built-in defaults.
 */
typedef struct TianyanConfigC {
  /*
   Platform hostname, e.g. `"qc.zdxlz.com"`. `NULL` → default.
   */
  const char *domain;
  /*
   File path for the JSON credentials file. `NULL` → default platform path.
   */
  const char *credentials_path;
  /*
   Whether to persist credentials to disk after login/refresh (default: `true`).
   */
  bool save_credentials;
  /*
   Whether to re-login automatically when the stored token expires (default: `true`).
   */
  bool auto_refresh;
} TianyanConfigC;

/*
 Return the machine-code identifier of the backend (e.g. `"tianyan-287"`).

 The returned pointer is valid for the lifetime of `backend` and **must not**
 be freed by the caller.
 */
const char *tianyan_backend_name(const struct TianyanBackendC *backend);

/*
 Return the user-friendly display name of the backend.

 The returned pointer is valid for the lifetime of `backend` and **must not**
 be freed by the caller.
 */
const char *tianyan_backend_display_name(const struct TianyanBackendC *backend);

/*
 Return the operational status of the backend as an integer code.

 | Code | Status              |
 |------|---------------------|
 | 0    | Running             |
 | 1    | Calibration         |
 | 2    | UnderMaintenance    |
 | 3    | OffLine             |
 | -1   | Unknown             |
 */
int tianyan_backend_status(const struct TianyanBackendC *backend);

/*
 Return the pricing model of the backend as an integer code.

 | Code | Pricing |
 |------|---------|
 | 1    | Free    |
 | 2    | Paid    |
 | -1   | Unknown |
 */
int tianyan_backend_toll(const struct TianyanBackendC *backend);

/*
 Return `true` if the backend is in `Running` status and accepting jobs.
 */
bool tianyan_backend_is_available(const struct TianyanBackendC *backend);

/*
 Write the total number of physical qubits in the backend configuration to `out_num_qubits`.

 This may download the backend configuration on first use and reuses the cached
 configuration afterwards. Disabled qubits are included in this count.

 Returns `true` on success and `false` on error. On error, call
 `tianyan_last_error()` for details.
 */
bool tianyan_backend_num_qubits(const struct TianyanBackendC *backend, uintptr_t *out_num_qubits);

/*
 Free a `TianyanBackend` returned by any API function.

 Passing `NULL` is safe and does nothing.
 */
void tianyan_backend_free(struct TianyanBackendC *backend);

/*
 Free an array of `TianyanBackend` pointers returned by `tianyan_platform_list_backends()`.

 This frees each individual backend and the array itself.
 Passing `NULL` for `backends` is safe and does nothing.
 */
void tianyan_backend_list_free(struct TianyanBackendC **backends, uintptr_t len);

/*
 Submit circuits on this backend with the default calibration mode (`Auto`).

 - `circuits`: array of `n_circuits` null-terminated QCIS strings.
 - `shots`: number of measurement shots per circuit.

 Returns a heap-allocated `TianyanTask` on success, `NULL` on error.
 The caller must free the returned pointer with `tianyan_task_free()`.
 */
struct TianyanTaskC *tianyan_backend_run(const struct TianyanBackendC *backend,
                                         const char *const *circuits,
                                         uintptr_t n_circuits,
                                         uintptr_t shots);

/*
 Like `tianyan_backend_run()` but always returns raw (uncalibrated) counts.
 */
struct TianyanTaskC *tianyan_backend_run_raw(const struct TianyanBackendC *backend,
                                             const char *const *circuits,
                                             uintptr_t n_circuits,
                                             uintptr_t shots);

/*
 Like `tianyan_backend_run()` but with an explicit calibration mode.

 `mode`: 0 = Auto, 1 = Enabled, 2 = Disabled.
 */
struct TianyanTaskC *tianyan_backend_run_with_mode(const struct TianyanBackendC *backend,
                                                   const char *const *circuits,
                                                   uintptr_t n_circuits,
                                                   uintptr_t shots,
                                                   int mode);

/*
 Retrieve the last error message set on this thread.

 Returns `NULL` if no error has occurred since the last successful call.
 The returned string is heap-allocated and **must** be freed with
 `tianyan_string_free()`.
 */
char *tianyan_last_error(void);

/*
 Clear the last error stored for this thread.
 */
void tianyan_error_clear(void);

/*
 Free a `char*` string that was returned by any `cqlib_tianyan` API function.

 Passing `NULL` is safe and does nothing.
 */
void tianyan_string_free(char *s);

/*
 Authenticate with the Tianyan platform using an API key.

 Credentials are saved to the default path (`~/.cqlib/tianyan/credentials.json`)
 so subsequent calls can use `tianyan_platform_from_credentials()`.

 Returns a heap-allocated `TianyanPlatform` on success, `NULL` on error.
 The caller must free the returned pointer with `tianyan_platform_free()`.
 */
struct TianyanPlatformC *tianyan_platform_login(const char *api_key);

/*
 Like `tianyan_platform_login()` but with a custom configuration.

 Pass `NULL` for `config` to use the default configuration.
 */
struct TianyanPlatformC *tianyan_platform_login_with_config(const char *api_key,
                                                            const struct TianyanConfigC *config);

/*
 Load previously saved credentials from disk.

 If the access token has expired, re-logs in automatically using the saved
 API key (requires `auto_refresh = true`, the default).

 Returns a heap-allocated `TianyanPlatform` on success, `NULL` on error.
 The caller must free the returned pointer with `tianyan_platform_free()`.
 */
struct TianyanPlatformC *tianyan_platform_from_credentials(void);

/*
 Like `tianyan_platform_from_credentials()` but with a custom configuration.

 Pass `NULL` for `config` to use the default configuration.
 */
struct TianyanPlatformC *tianyan_platform_from_credentials_with_config(const struct TianyanConfigC *config);

/*
 Free a `TianyanPlatform` returned by any `tianyan_platform_*` function.

 Passing `NULL` is safe and does nothing.
 */
void tianyan_platform_free(struct TianyanPlatformC *platform);

/*
 Fetch all available quantum backends from the platform.

 On success writes the backend count to `*out_len` and returns a
 heap-allocated array of `TianyanBackend` pointers (length `*out_len`).
 Each element **and** the array itself must be freed by calling
 `tianyan_backend_list_free(backends, len)`.

 Returns `NULL` on error; call `tianyan_last_error()` for details.
 */
struct TianyanBackendC **tianyan_platform_list_backends(const struct TianyanPlatformC *platform,
                                                        uintptr_t *out_len);

/*
 Return the backend with the given name (case-sensitive).

 Returns a heap-allocated `TianyanBackend` on success, `NULL` if not found.
 The caller must free the returned pointer with `tianyan_backend_free()`.
 */
struct TianyanBackendC *tianyan_platform_get_backend(const struct TianyanPlatformC *platform,
                                                     const char *name);

/*
 Submit circuits directly without first fetching a backend handle.

 Equivalent to `tianyan_platform_get_backend(platform, device_name)` followed
 by `tianyan_backend_run(...)`, but skips the extra device-list network round-trip.

 - `circuits`: array of `n_circuits` null-terminated QCIS strings.
 - `shots`: number of measurement shots per circuit.
 - `device_name`: target backend identifier (case-sensitive).

 Returns a heap-allocated `TianyanTask` on success, `NULL` on error.
 The caller must free the returned pointer with `tianyan_task_free()`.
 */
struct TianyanTaskC *tianyan_platform_submit(const struct TianyanPlatformC *platform,
                                             const char *const *circuits,
                                             uintptr_t n_circuits,
                                             uintptr_t shots,
                                             const char *device_name);

/*
 Return the name of the backend device this task was submitted to.

 The returned pointer is valid for the lifetime of `task` and **must not**
 be freed by the caller.
 */
const char *tianyan_task_device_name(const struct TianyanTaskC *task);

/*
 Return the number of measurement shots requested per circuit.
 */
uintptr_t tianyan_task_shots(const struct TianyanTaskC *task);

/*
 Return the number of submitted circuits (= number of query IDs).
 */
uintptr_t tianyan_task_num_circuits(const struct TianyanTaskC *task);

/*
 Return a heap-allocated array of null-terminated query-ID strings.

 Writes the count to `*out_len`. Each string and the array itself must be
 freed by calling `tianyan_task_ids_free(ids, len)`.

 Returns `NULL` on error.
 */
char **tianyan_task_ids(const struct TianyanTaskC *task, uintptr_t *out_len);

/*
 Free the array returned by `tianyan_task_ids()`.
 */
void tianyan_task_ids_free(char **ids, uintptr_t len);

/*
 Free a `TianyanTask` returned by any `tianyan_backend_run*()` or `tianyan_platform_submit()`.

 Passing `NULL` is safe and does nothing.
 */
void tianyan_task_free(struct TianyanTaskC *task);

/*
 Block until **all** circuits have results, then return the list.

 Readout error mitigation is applied according to the calibration mode set
 when the task was submitted (default: `Auto`).

 - `timeout_secs`: maximum wall-clock seconds to wait.
 - `poll_interval_secs`: seconds between consecutive poll requests.

 Returns a heap-allocated `TianyanResultList` on success, `NULL` on error.
 The caller must free it with `tianyan_result_list_free()`.
 */
struct TianyanResultList *tianyan_task_wait(const struct TianyanTaskC *task,
                                            double timeout_secs,
                                            double poll_interval_secs);

/*
 Like `tianyan_task_wait()` but always returns raw (uncalibrated) counts,
 regardless of the calibration mode set at submission time.
 */
struct TianyanResultList *tianyan_task_wait_raw(const struct TianyanTaskC *task,
                                                double timeout_secs,
                                                double poll_interval_secs);

/*
 Query the platform once and return whichever results are already ready.

 Circuits that have not yet completed are absent from the returned list.
 For polling until all circuits complete, use `tianyan_task_wait()`.

 Returns a heap-allocated `TianyanResultList` on success, `NULL` on error.
 The caller must free it with `tianyan_result_list_free()`.
 */
struct TianyanResultList *tianyan_task_status_snapshot(const struct TianyanTaskC *task);

/*
 Return the number of results in the list.
 */
uintptr_t tianyan_result_list_len(const struct TianyanResultList *list);

/*
 Return the task/query ID for the result at index `i`.

 The returned pointer is valid for the lifetime of `list` and **must not**
 be freed by the caller. Returns `NULL` if `i` is out of bounds.
 */
const char *tianyan_result_task_id(const struct TianyanResultList *list, uintptr_t i);

/*
 Return the number of shots for the result at index `i`.
 */
uintptr_t tianyan_result_shots(const struct TianyanResultList *list, uintptr_t i);

/*
 Return the number of measured qubits for the result at index `i`.
 */
uintptr_t tianyan_result_num_qubits(const struct TianyanResultList *list, uintptr_t i);

/*
 Return the measurement counts for result `i` as a JSON object string.

 Example: `{"00": 512, "11": 488}`

 The returned string is heap-allocated and **must** be freed by the caller
 with `tianyan_string_free()`. Returns `NULL` on error or out-of-bounds `i`.
 */
char *tianyan_result_counts_json(const struct TianyanResultList *list, uintptr_t i);

/*
 Free a `TianyanResultList` returned by any `tianyan_task_wait*()` or
 `tianyan_task_status_snapshot()` function.

 Passing `NULL` is safe and does nothing.
 */
void tianyan_result_list_free(struct TianyanResultList *list);

#endif  /* CQLIB_TIANYAN_H */
