[package]
name = "binding-python"
version = "0.1.0-beta.1"
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true
publish = false

[lib]
name = "_cqlib_tianyan"
crate-type = ["cdylib", "rlib"]

[dependencies]
pyo3 = { version = "0.29", features = ["extension-module", "abi3-py310"] }
cqlib-tianyan = { path = "../cqlib-tianyan", version = "0.1.0-beta.1" }
cqlib-core = { workspace = true }
rustworkx-core = { workspace = true }
